
-- create table

CREATE TABLE wrestlers (
    id INT NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(32),
    last_name VARCHAR(32),
    gender VARCHAR(1),
    club_name VARCHAR(32),
    PRIMARY KEY (id)
);

-- insert all names

INSERT INTO wrestlers (    
    first_name,
    last_name,
    club_name,
    gender
)
VALUES ( "Asmaa", "Gharir", "Wolves", "f" ),
( "Max", "Thayer", "Gladiators", "m" ),
( "Jake", "mclernon", "Gladiators", "m" ),
( "Benji", "Halley", "Punishers", "m" ),
( "Merceydes", "Floyd", "Wolves", "f" ),
( "Darcey McLernon", "(GLAD)", "Gladiators", "f" ),
( "Kilian", "Roberts", "Subiaco", "m" ),
( "Aadam", "Mowafy", "Wolves", "m" ),
( "Francois", "Heyns", "Warriors", "m" ),
( "Tait", "Anderson", "Gladiators", "m" ),
( "Jake Raymond", "Criddle", "Wolves", "m" ),
( "Phoenix", "Evans-Brown", "Gladiators", "m" ),
( "Jack", "Graham-Arho", "Warriors", "m" ),
( "Maymoonah", "Mowafy", "Wolves", "f" ),
( "Louis", "Heyns", "Warriors", "m" ),
( "Ibrahim", "Loder", "Wolves", "m" ),
( "Dominic", "Bishop", "Punishers", "m" ),
( "Dakota", "Bishop", "Punishers", "m" ),
( "Oscar", "Gray", "Evolution", "m" ),
( "Ollie", "Jones", "Gladiators", "m" ),
( "Jules", "chabbert", "Fremantle", "m" ),
( "Japleen", "Kaur", "Gladiators", "f" ),
( "Isaac", "Tyler-Hills", "Warriors", "m" ),
( "Finn", "Bald", "Gladiators", "m" ),
( "Aaliyah", "Koha", "Punishers", "f" ),
( "Chanelle", "Piipponen", "Gladiators", "f" ),
( "Daniel", "Starkowitz", "Independent", "m" ),
( "Muhummed", "Loder", "Wolves", "m" ),
( "Gray", "Moffat-Clarke", "Fremantle", "m" ),
( "Taonga -manaakitanga", "Manuel", "Gladiators", "f" ),
( "Carl", "Jankowitz", "Warriors", "m" ),
( "Yusuf", "Loder", "Wolves", "m" ),
( "Mia", "Tesanovic", "Wolves", "f" ),
( "Ian", "Cook", "Punishers", "m" ),
( "Tom", "Barns", "Gladiators", "m" ),
( "Mia", "Tesanovic", "Wolves", "f" ),
( "Jamil", "Vacca", "Gladiators", "m" ),
( "Jye", "Miller", "Fremantle", "m" ),
( "Taaniel", "Piiskoppel", "Wolves", "m" ),
( "Thomas", "Leaver", "Subiaco", "m" ),
( "Dyota", "Tanuwibawa", "Subiaco", "m" ),
( "Scott", "Miotto", "Wolves", "m" ),
( "Stephen", "Erceg", "Gladiators", "m" ),
( "Shantaram", "Maharaj", "Punishers", "m" ),
( "Shaun", "Johnston", "Gladiators", "m" ),
( "Taylor", "Pickering", "Gladiators", "m" ),
( "Petrus", "Palm", "Warriors", "m" ),
( "Oliver", "Hickey", "Subiaco", "m" ),
( "Abdalla", "Biayda", "Punishers", "m" ),
( "anthony", "drilich", "Next Gen", "m" ),
( "Lexi", "Hamilton-Smith", "Warriors", "f" ),
( "Melissa", "Debono", "Gladiators", "f" ),
( "Nima", "Behrouz", "Gladiators", "m" ),
( "Alireza", "Rezvani", "Gladiators", "m" ),
( "Ravi", "Schreefel", "Gladiators", "m" ),
( "ray", "holtham", "Evolution", "m" ),
( "Theodore", "Murphy-Jelley", "Gladiators", "m" ),
( "Nicholas", "Freitas", "Wolves", "m" ),
( "Kyle", "Skiba", "Punishers", "m" ),
( "Leo", "Tesanovic", "Wolves", "m" ),
( "Oskar", "Paino-Povey", "Warriors", "m" ),
( "Jacob", "Cole", "Subiaco", "m" ),
( "Tom", "Barns", "Gladiators", "m" ),
( "Scott", "Miotto", "Wolves", "m" ),
( "Taaniel", "Piiskoppel", "Wolves", "m" ),
( "Ando", "Lehtmets", "Wolves", "m" ),
( "anthony", "drilich", "Next Gen", "m" ),
( "Leo", "Tesanovic", "Wolves", "m" ),
( "Joshua", "Katene", "Wolves", "m" ),
( "Milla", "Graham-Arho", "Warriors", "f" ),
( "Jesse", "Armstrong", "Evolution MMA", "m" );